---
- name: (RedHat) Install repository management packages
  package:
    name:
      - epel-release
      - yum-utils
    state: present

- name: (RedHat) Add Remi repository GPG key
  rpm_key:
    state: present
    key: "https://rpms.remirepo.net/RPM-GPG-KEY-{{ target }}"
  vars:
    target: >-
      {{ "remi" if version|int == 7
      else "remi2018" }}
    version: "{{ ansible_distribution_major_version }}"

- name: (RedHat) Add Remi repository
  package:
    name: >-
      https://rpms.remirepo.net/enterprise/remi-release-
      {{- ansible_distribution_major_version }}.rpm
    state: present

# FIXME: Find a better way to enable a repo prior to installing packages
# FIXME: Idempotence is broken on this task. Anything we can hook onto?
- name: (RedHat) Enable Remi PHP repository
  raw: "{{ command }}{{ target }}"
  changed_when: result.rc > 0
  register: result
  vars:
    command: >-
      {{ "yum-config-manager --enable remi-php" if version|int == 7
      else "dnf module enable -y php:remi-" }}
    target: >-
      {{ php_version_flat if version|int == 7
      else php_version }}
    version: "{{ ansible_distribution_major_version }}"
